name: System Check

on: [push, pull_request]

jobs:
  system_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run syscheck.sh
      run: bash syscheck.sh 
